title: A New Doghouse
author: Xiaoya Liang
email: xiaoyaliang93@gmail.com
description: > # this means to ignore newlines until "baseurl:"
# Write an awesome description for your new site here. You can edit this line in _config.yml. 
# It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  This is a supportive website for my MFA thesis project. 
  It is a special addition to the film I'm making；it is also a learning process for a new career. 

theme: minima

# social links
twitter_username: xiaoyaliang # DO NOT include the @ character, or else the build will fail!
github_username:  xiaoyaliang # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
